Implement internal and external mode.
cfrg/draft-irtf-cfrg-opaque pull request #168
Opened 2021-04-01 01:10 UTC by chris-wood

Implements #154. Starting as a draft while we work through interop.

2021-04-04 10:22 UTC, kevinlewi commented on poc/opaque_core.sage
> +        auth_tag = self.config.mac.mac(auth_key, inner_env.serialize() + cleartext_creds.serialize())
auth_tag needs to be computed over the mode and the nonce as well, not just the inner_env and cleartext_creds

2021-04-04 20:37 UTC, kevinlewi commented on poc/test_opaque_ake.sage
> +                inputs["client_public_key"] = to_hex(pkU_bytes)
One problem: when these are derived from the randomized_pwd seed, these are no longer inputs -- they are intermediate values. In particular, I don't think these were updated as their corresponding values when derived from the randomized_pwd seed, and so they end up not matching...

2021-04-06 16:30 UTC, bytemare requested changes

2021-04-06 16:30 UTC, bytemare commented on poc/opaque_core.sage
> +            secret_creds = SecretCredentials(client_private_key)
We're dropping `SecretCredentials` and encrypt `client_private_key` directly

2021-04-06 16:30 UTC, bytemare commented on poc/opaque_core.sage
> +        auth_tag = self.config.mac.mac(auth_key, inner_env.serialize() + cleartext_creds.serialize())
Agreed, that's where the vectors don't match :)

2021-04-06 21:46 UTC, bytemare commented on poc/test_opaque_ake.sage
> +                inputs["client_public_key"] = to_hex(pkU_bytes)
I confirm

2021-04-06 21:50 UTC, bytemare commented
Something quite peculiar: P384 and P512 in the internal mode only have a public key in the registration upload vectors that doesn't correspond to either the client public key vector (that is false anyway) and the recovered public key from the password.

In all other vectors, the public key in the registration upload is correct.

2021-04-15 13:26 UTC, merged