Add application considerations.
cfrg/draft-irtf-cfrg-opaque pull request #199
Opened 2021-04-24 15:36 UTC by chris-wood

Opening as a draft to discuss. Are there other considerations we want to add?

2021-04-25 22:19 UTC, bytemare commented on draft-irtf-cfrg-opaque.md
> +    email: d@bytema.re
❤️

2021-04-26 13:42 UTC, bytemare commented
Do you mean with regard to #173?

2021-05-26 22:23 UTC, chris-wood commented
@bytemare I also included #204 changes here. (Do you think more needs to be said to close out that issue?)

2021-05-28 13:15 UTC, bytemare requested changes

2021-05-28 13:15 UTC, bytemare commented on draft-irtf-cfrg-opaque.md
> +is also in use, the server will not complete the protocol. This allows an attacker
```suggestion
is already in use, the server will not complete the protocol. This allows an attacker
```

2021-05-28 19:39 UTC, bytemare approved these changes

2021-05-28 19:42 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
> +given client identity is registered. Applications should mitigate against
I think this is resolved?

2021-05-29 12:17 UTC, bytemare commented on draft-irtf-cfrg-opaque.md
> +given client identity is registered. Applications should mitigate against
Yes it is -- I resolved this yesterday when we talked about it

2021-06-02 19:09 UTC, kevinlewi approved these changes
This is very well-written. Thank you!

2021-06-02 19:19 UTC, merged