Contradictory statements on draft
cfrg/draft-irtf-cfrg-opaque pull request #225
Opened 2021-06-24 18:58 UTC by jansen44

I've been studying OPAQUE for the last month or so (and I must say I'm in love with it). Yesterday I was reading the draft and found two statements that looked a little contradictory. 

I sent an email asking if one of them was really an accident and @bytemare (at least I think it was him lol) replied me saying that I was correct and also that you guys were accepting pull requests, so here I am :blush:.

- The first statement is the one that that I sent on the email: this statement at the fourth section, second paragraph:  "OPAQUE allows applications to either provide custom client private and public keys for authentication, or to generate them internally. [...] These two options are defined as the "internal" and "external" modes, respectively. [...]"... I think that "internal mode" would better refer to "generate keys internally", so the "respectively" term was kinda misleading.
- The second statement is at the fourth section, third paragraph: "The following types of application credential information are considered: client_private_key: The encoded client private key for the AKE protocol." Every other item on this list was indeed used and stored inside the `CleartextCredentials` struct, but client_private_key was totally ignored, so I guess it's actually not a credential information to be considered (at least at this context).

I don't know if any of what I said really makes sense to you guys, but I hope it does help ✌🏻 .

2021-06-26 09:28 UTC, bytemare approved these changes

2021-06-28 14:47 UTC, chris-wood requested changes

2021-06-28 14:47 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
> -- client_private_key: The encoded client private key for the AKE protocol.
This is still used (for external mode), so I think we should keep this.

2021-06-29 01:45 UTC, chris-wood approved these changes

2021-06-29 01:46 UTC, merged