Ensure constant-time fake credential response
cfrg/draft-irtf-cfrg-opaque pull request #227
Opened 2021-06-26 11:24 UTC by bytemare

Closes #219

2021-06-28 14:57 UTC, chris-wood requested changes

2021-06-28 14:57 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
> +the server must respond to the credential request to fake the existence of the record.
```suggestion
the server MUST respond to the credential request to fake the existence of the record.
```

2021-06-28 14:57 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
> +In the generated test vectors from {{fake-vectors}}, we use `client_public_key` for this record's
This should move to the test vector section, rather than be listed here.

2021-06-28 14:57 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
> +avoiding timing leaks.
```suggestion
It is RECOMMENDED that a fake client record is created once (e.g. as the first user record
of the application) and stored alongside legitimate client records. This allows servers to locate
the record in time comparable to that of a legitimate client record.
```

2021-06-28 23:16 UTC, chris-wood commented
@bytemare, sorry, I meant to suggest that the comment could go [here](https://cfrg.github.io/draft-irtf-cfrg-opaque/draft-irtf-cfrg-opaque.html#section-appendix.c), at the end of the text in the start of Appendix C.

2021-06-29 00:30 UTC, chris-wood requested changes
Can we move the text up to the start of Appendix C?

2021-06-29 01:24 UTC, bytemare commented
> @bytemare, sorry, I meant to suggest that the comment could go [here](https://cfrg.github.io/draft-irtf-cfrg-opaque/draft-irtf-cfrg-opaque.html#section-appendix.c), at the end of the text in the start of Appendix C.

Ah, of course, you mean "Test Vectors", right?

2021-06-29 01:41 UTC, chris-wood approved these changes

2021-06-29 01:41 UTC, merged