Use the OPRF DeriveKeyPair function and update OPRF usage
cfrg/draft-irtf-cfrg-opaque pull request #329
Opened 2022-02-02 22:46 UTC by chris-wood

Closes #328.
Closes #241.

2022-02-03 00:51 UTC, chris-wood commented
@stef I reverted the change in [eae5040](https://github.com/cfrg/draft-irtf-cfrg-opaque/pull/329/commits/eae5040eec78f69eaf77a3e7b59900e40f1899ef).

2022-02-03 16:35 UTC, bytemare commented on poc/test_opaque_ake.sage
> +    (_, _) = group.key_gen()
what does that do?

2022-02-03 21:28 UTC, chris-wood commented on poc/test_opaque_ake.sage
> +    (_, _) = group.key_gen()
It fixes the deterministic test vector issue @stef pointed out. I'll address this (by removing it) in a future change that _does not_ make any protocol changes.

2022-02-03 21:29 UTC, bytemare requested changes

2022-02-03 21:29 UTC, bytemare commented on draft-irtf-cfrg-opaque.md
> +  (oprf_key, _) = DeriveKeyPair(seed, "OPAQUE")
```suggestion
  (oprf_key, _) = DeriveKeyPair(seed, "OPAQUE-DeriveKeyPair")
```

2022-02-03 21:31 UTC, bytemare requested changes

2022-02-03 21:31 UTC, bytemare commented on draft-irtf-cfrg-opaque.md
> +  (oprf_key, _) = DeriveKeyPair(seed, "OPAQUE")
```suggestion
  (oprf_key, _) = DeriveKeyPair(seed, "OPAQUE-DeriveKeyPair")
```

2022-02-03 21:34 UTC, chris-wood commented
@stef are you able to verify the test vectors in this PR?

2022-02-03 21:34 UTC, bytemare approved these changes

2022-02-03 21:37 UTC, stef commented
with pleasure!

2022-02-03 21:43 UTC, bytemare commented
lgtm

2022-02-03 22:07 UTC, bytemare commented
Does this close #298 ?

2022-02-04 00:19 UTC, chris-wood commented
> Does this close #298 ?

I don't think so. I'll address those in a followup change.

2022-02-04 15:18 UTC, stef commented
i checked, and updated my implementation. lgtm.

2022-02-04 15:18 UTC, chris-wood commented
Excellent! Merging.

2022-02-04 15:18 UTC, merged