Adding in formal definitions of state structures
cfrg/draft-irtf-cfrg-opaque pull request #362
Opened 2022-05-30 11:11 UTC by kevinlewi

Closes #291.

Adding in formal definitions for `ClientState`, `ServerState`, `ClientAkeState`, and `ServerAkeState`.

Note that for the password field, which can be variable-length, I set the type to `opaque password<1..2^16-1>`, even though this is not a strict requirement. I also set blind to be `opaque blind<1..2^16-1>`. Let me know if these should be changed!

2022-05-30 11:35 UTC, chris-wood requested changes
The actual data structure is an implementation-specific decision and should not be mandated like this, so I think we ought to remove some details and just say list the things that can be referenced.

2022-05-30 11:35 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
> +```
```suggestion
```

2022-05-30 11:35 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
> +```
```suggestion
```

2022-05-30 11:35 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
> +The client AKEstate `ClientAkeState` mentioned in {{online-phase}} has the
```suggestion
The client AKE state `ClientAkeState` mentioned in {{online-phase}} has the
```

2022-05-30 11:35 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
> +
```suggestion
```

2022-05-30 11:35 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
> +
```suggestion
```

2022-05-30 14:08 UTC, stef commented
i agree with Chris that these are implementation specific. so **none** of this should be binding. however i see value
  - for implementers as a kind of checklist,
  - for interoperability for suggesting minimum/maximum size for variable sized fields - this would enable converters between different implementations,
  - most importantly lifetime, sensitivity/confidentiality of these fields (for example can they be serialized to storage, do they need to be encrypted, will they lose importance after the next step, etc)

i understand that much of this is already specified through-out of this document, and thus i think this is merely a convenience feature for implementers who don't have to piece this information together from various parts of the spec. i guess that's a lot of words for saying put this whole thing into a non-binding appendix.

2022-05-30 23:11 UTC, kevinlewi commented
Thanks for the feedback. I agree that it shouldn't be required for implementations to implement this state. However, shouldn't we still have struct definitions for these, since they are referenced in the functions? Just going off of the discussion in Issue #291 which brought this to our attention in the first place...

Comment from @armfazh :
> So, either formally specifying what the state contains, or removing at all the state structure are both good alternatives. Currently, it is specified something in between.

2022-05-30 23:13 UTC, chris-wood commented
> However, shouldn't we still have struct definitions for these, since they are referenced in the functions? 

No, I don't think so. It is sufficient to simply say what the data structure must contain. It is not necessary to say anything about how that data structure is implemented.

2022-05-30 23:18 UTC, kevinlewi commented
I see, got it. Alright, I committed your suggestions which removed the formal specifications. This PR then doesn't do too much, other than separate ClientState/ServerState from ClientAkeState/ServerAkeState. 

Are we still good to close #291 after this lands?

2022-06-01 22:36 UTC, bytemare approved these changes

2022-06-05 07:47 UTC, merged