Fix h2c submodule and add more info to Fake vectors.
cfrg/draft-irtf-cfrg-opaque pull request #396
Opened 2023-03-04 03:44 UTC by armfazh

Changes:
 - Removes duplicated submodule for h2c. Better to use the one inside the voprf module.
 - Exports more values to make the Fake case reproducible.

No changes on test vectors, just more verbose info for the `Fake=True` cases.

2023-03-10 16:31 UTC, bytemare approved these changes
Works for me ! Thank you :)

2023-03-10 18:35 UTC, kevinlewi requested changes
@armfazh: Thanks! I'm struggling to understand the need for the changes to make the fake case reproducible, though...

Why do we need to include the input parameters to generate KE1 (e.g. password, client_nonce, etc.), and view KE1 as an output (as opposed to an input)? Shouldn't KE1 be an input, and KE2 be the only output?

2023-03-14 15:35 UTC, armfazh commented
It wasn't required at all. Test vectors are ok as is.
I just update this PR with changes only for h2c submodule.

2023-03-14 19:16 UTC, kevinlewi approved these changes
LGTM! Thanks!

2023-03-17 19:43 UTC, bytemare commented on poc/opaque_ake.sage
> +            "OPRF": self.config.oprf_suite.identifier,
Good catch! I must have forgotten to commit that

2023-03-20 18:53 UTC, chris-wood approved these changes

2023-03-20 18:53 UTC, chris-wood commented
Thanks, @armfazh! Merging.

2023-03-20 18:53 UTC, merged