Address Eric Crockett's review comments.
cfrg/draft-irtf-cfrg-opaque pull request #56
Opened 2020-09-16 13:12 UTC by chris-wood

2020-09-18 12:59 UTC, chris-wood commented
@hugokraw this PR should be good to go!

2020-09-19 00:54 UTC, hugokraw requested changes

2020-09-19 00:57 UTC, hugokraw commented
I am afraid that I did not pushed  my comments (which I wrote them a couple of days ago) before for you to see.  Sorry for that. Eric also asked for a couple of clarifications to add (on the need of forward secrecy and something else). If you need text from me let me know.

2020-09-19 11:52 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
> +We also assume the existence of a function `KeyGen` from {{I-D.irtf-cfrg-voprf}}, which
It's currently not part of the OPRF API, so I left it off the list above. If the OPRF draft changes, we can change this too.

2020-09-19 11:53 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
> +Specification of the AKE is out of scope for this document. {{instantiations}} describes
What I meant is that this document doesn't intend to specify, describe, etc *new* AKEs, but I see how this is confusing. I'll just remove it.

2020-09-19 11:54 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
> -from auth_data (step 9).
I think this entire paragraph is probably obsolete. I'll just remove it.

2020-09-19 11:55 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
> +As discussed in {{security-considerations}}, each AKE protocol requires KCI resistance.
That's a nice rewrite -- I'll take it!

2020-09-19 12:23 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
> +pkU, idU, or IdS in the `Credentials.secret_credentials` structure (step 5) if secrecy
Fixed!

2020-09-19 12:23 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
>  with interleaved and combined messages (while preserving the internal ordering of
Fixed!

2020-09-19 12:25 UTC, chris-wood commented
@hugokraw Thanks for the feedback -- I incorporated your comments. I also added some additional changes on top. Namely:

- Fix the auth_tag size to the output of HMAC. (One less variable-length thing to worry about.)
- Change how the auth_tag is computed. Previously, it did not include the length of the ciphertext or auth_data, which was worrisome. Now it's computed over the structure:

```
struct {
  opaque nonce[32];
  opaque ct<1..2^16-1>;
  opaque auth_data<0..2^16-1>;
} InnerEnvelope;
```

which includes the length of `ct` and `auth_data`.

Please let me know what you think!

2020-09-21 23:51 UTC, chris-wood commented
@hugokraw, friendly bump! Please feel free to edit the PR directly if that's easier for you. :-)

2020-09-22 00:44 UTC, hugokraw commented on draft-irtf-cfrg-opaque.md
> +possible if all - or a minimal number of - servers are compromised.)
Add a reference to the OPAQUE paper at the end of the parentheses

2020-09-22 00:44 UTC, hugokraw approved these changes

2020-09-22 00:45 UTC, hugokraw commented
Sorry for the delay in responding to the latest changes. I was busy welcoming my second grandson... :-)

2020-09-22 01:56 UTC, merged