Update to some minor details of the current VOPRF draft
cfrg/draft-irtf-cfrg-opaque pull request #92
Opened 2020-11-27 20:56 UTC by claucece

2020-11-30 15:01 UTC, chris-wood requested changes
Thanks! I've been meaning to get around to this. I think some things regressed, which I've noted. Otherwise, this is good.

2020-11-30 15:43 UTC, claucece commented on draft-irtf-cfrg-opaque.md
> +generates an OPRF private key. OPAQUE only requires an OPRF private key.
I'll revert it ;)

2020-11-30 15:43 UTC, claucece commented on draft-irtf-cfrg-opaque.md
> +: An encoded element in the OPRF group.
The data returned from the OPRF functions is always already encoded/serialized, so no need to specify how to encode.

2020-11-30 15:44 UTC, claucece commented on draft-irtf-cfrg-opaque.md
> +determined. A natural approach is to tie idU to the identity the user uses
Ah, ok. Reverting this.

2020-11-30 15:45 UTC, claucece commented on draft-irtf-cfrg-opaque.md
> +: An encoded element in the OPRF group.
Except for the scalar that is returned from `blind`.

2020-11-30 15:46 UTC, claucece commented on draft-irtf-cfrg-opaque.md
> +3. Create RequestMetadata metadata with Serialize(r)
Agreed ;)

2020-11-30 16:00 UTC, claucece commented on draft-irtf-cfrg-opaque.md
> +    opaque id<1..2^16-1>; /* optional */
Done.

2020-12-01 14:56 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
> +: An encoded element in the OPRF group.
👍

2020-12-01 14:56 UTC, chris-wood commented on draft-irtf-cfrg-opaque.md
> +    opaque id<1..2^16-1>;
```suggestion
```

2020-12-01 14:56 UTC, chris-wood approved these changes

2020-12-01 15:40 UTC, merged